### PR TITLE
Handle files without record variables; fix #4

### LINKED ISSUE #4: Responder may hang when serving files without any record variables
[record_generator](https://github.com/pacificclimate/pydap.responses.netcdf/blob/90134a01f5980ecbfb85096734db05fc00765da6/src/pydap/responses/netcdf/__init__.py#L126), which iterates over a files record variables, may not exit the `while True:` loop if the netCDF file has _no_ record variables. This results in the process just hanging.

However, this error does not occur with _all_ data requests made against files without record variables, which is puzzling.

### PR DESCRIPTION
**Pull request by corviday**
Addresses [a hung process when serving data from some BCCAQv2 files](https://github.com/pacificclimate/pdp/issues/107). Some of the BCCAQv2 files have the "time" dimension set to limited, instead of unlimited (possibly as a result of [this data processing script](https://github.com/pacificclimate/data-prep-actions/blob/86e2059d3b4c3126ebcaa1bdb1b1986114d2001d/actions/normalize-pdp-time/remove_time_offset.py)). These files don't have any unlimited dimensions and therefore lack record variables (variables with unlimited dimensions) entirely.

There are two generators that handle writing out variables: `nonrecord_input()` and `record_generator()` They're chained together with `nonrecord_input()` called first. Separate generators for record and nonrecord variables are required because the netCDF standards specify different disk layouts for record variables so new data can be appended easily.

`record_generator()` does not currently handle the case where there are zero record variables. This PR adds a check to catch the case where there are no record variables, and yields `None` if so.

### CODE REVIEW

**Comment by corviday** [comment]
Question for @jameshiebert: is this the pythonic way to make an empty generator?

**Review by jameshiebert — CHANGES_REQUESTED** [review]
So, I don't think that this will do what you want. Instead of ending the iteration without returning anything, it will actually yield a `None` object, which is not what we want (and chances are good that it will break the pipeline later on).

Here's an example:

```python
>>> def empty_generator():
...     yield None
... 
>>> [ x for x in empty_generator() ]
[None]
```

See, you don't want `None` in there, just an empty list.

What I *think* that you want is to actually return from the generator, which is weird but also [totally normal](https://docs.python.org/3/howto/functional.html#generators) and might be the right thing to do.

```
>>> def empty_generator():
...     return
...     yield
... 
>>> [ x for x in empty_generator() ]
[]
```

Alternatively you could actually `raise StopIteration` which is the end result of returning from a generator:

```
>>> def empty_generator():
...     raise StopIteration
...     yield
... 
>>> [ x for x in empty_generator() ]
[]
```

However, there is [some discussion out there](https://stackoverflow.com/questions/13243766/python-empty-generator-function#comment51819885_28285860) that this is taking advantage of internal behaviour that might change, and thus is not future proof. I'd tend to agree.

One thing that I think might improve this code is... why is there a `while True` there in the first place, if it manually raises a `StopIteration` in the first place? `var.next()` will raise a `StopIteration` when it's out of values... so the infinite loop with a break out is totally unnecessary.

```
>>> def finite_generator_with_infinite_loop():
...     while True:
...         for i in range(5):
...             yield i
...         raise StopIteration
... 
>>> [ x for x in finite_generator_with_infinite_loop() ]
[0, 1, 2, 3, 4]
>>> def finite_generator():
...     for i in range(5):
...         yield i
... 
>>> [ x for x in finite_generator() ]
[0, 1, 2, 3, 4]
```

The latter method is much better. So maybe we can just remove the `while` loop and be done with it?

Can you send me (or post) what cases you used to test this?

**Comment by corviday** [comment]
My diagnostic test case was: 
```
/downscaled_gcms/tasmin_day_BCCAQv2+ANUSPLIN300_CCSM4_historical+rcp45_r2i1p1_19500101-21001231.nc.nc?tasmin[2:8][32:32][739:739]
```
Other testing I did yesterday morning to make sure nothing new was broken by this fix was:
```bash
for file in $(cat bccaq_2_ids.csv) ; do wget 127.0.0.1:8000/data/downscaled_gcms/$file.nc.nc?pr[2:8][7:7][9:9] ; done
for file in $(cat bccaq_2_ids.csv) ; do wget 127.0.0.1:8000/data/downscaled_gcms/$file.nc.nc?tasmax[2:8][7:7][9:9] ; done
for file in $(cat bccaq_2_ids.csv) ; do wget 127.0.0.1:8000/data/downscaled_gcms/$file.nc.nc?tasmin[2:8][7:7][9:9] ; done
for file in $(cat gcms_archive_ids.csv) ; do wget 127.0.0.1:8000/data/downscaled_gcms_archive/$file.nc.nc?pr[5:9][7:7][9:9] ; done
```

bccaq_2_ids.csv contains URL-encoded unique IDs of every dataset in the bccaq_version_2 ensemble, extracted from the database. (Each dataset returns a 500 when you try to download the wrong variable, which I just ignored.) 

`gcms_archive_ids.csv` contains unique ids from the downscaled_gcms_archive ensemble, though a few of the names are misformatted and return 404 errors, which I also ignored.

I also did a handful of files in each ensemble with timestamps [5:1000] and [5:10000] but the same 1-cell small spatial extents. I looked at size of downloaded files and whether the download hung, but I didn't open them up and make sure the data was good (in fact, I think most of these downloads grab masked data.)

As far as more scattershot testing that actually looks at the data, it looks like my test cases were:
``` bash
#testing longer-than-full-timesteps
wget 127.0.0.1:8000/data/downscaled_gcms/pr_day_BCCAQv2+ANUSPLIN300_CanESM2_historical+rcp85_r1i1p1_19500101-21001231.nc.nc?pr[0:55152][120:120][323:325]&
#testing different slices - bccaq2
wget 127.0.0.1:8000/data/downscaled_gcms/tasmin_day_BCCAQv2+ANUSPLIN300_CCSM4_historical+rcp45_r2i1p1_19500101-21001231.nc.nc?tasmin[2:7][32:32][739:739]
wget 127.0.0.1:8000/data/downscaled_gcms/tasmin_day_BCCAQv2+ANUSPLIN300_CCSM4_historical+rcp45_r2i1p1_19500101-21001231.nc.nc?tasmin[2:8][32:32][739:739]
wget 127.0.0.1:8000/data/downscaled_gcms/tasmin_day_BCCAQv2+ANUSPLIN300_CCSM4_historical+rcp45_r2i1p1_19500101-21001231.nc.nc?tasmin[2:1000][32:32][739:739]
wget 127.0.0.1:8000/data/downscaled_gcms/tasmin_day_BCCAQv2+ANUSPLIN300_CCSM4_historical+rcp45_r2i1p1_19500101-21001231.nc.nc?tasmin[2:9][32:32][739:739]
#testing a different file - bccaq2
wget 127.0.0.1:8000/data/downscaled_gcms/tasmin_day_BCCAQv2+ANUSPLIN300_CCSM4_historical+rcp45_r2i1p1_19500101-21001231.nc.nc?tasmin[2:8][32:32][739:739]
wget 127.0.0.1:8000/data/downscaled_gcms/tasmin_day_BCCAQv2+ANUSPLIN300_CCSM4_historical+rcp45_r2i1p1_19500101-21001231.nc.nc?tasmin[2:7][32:32][739:739]
#testing different slices - bccaq1
wget 127.0.0.1:8000/data/downscaled_gcms_archive/pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+CanESM2_historical+rcp26_r1i1p1_19500101-21001231.nc.nc?tasmax[0:20][154:170][903:919]&
wget 127.0.0.1:8000/data/downscaled_gcms_archive/pr+tasmax+tasmin_day_BCSD+ANUSPLIN300+CanESM2_historical+rcp26_r1i1p1_19500101-21001231.nc.nc?tasmax[0:10][0:100][0:100]
```

**Comment by jameshiebert** [comment]
Hmmm, that sounds pretty comprehensive. Maybe by some magic the pipeline is accidentally resilient to a `None` stuffed in there...

**Comment by corviday** [comment]
I think [this](https://github.com/pacificclimate/pydap.responses.netcdf/pull/5/files#diff-79b78de6ebc6534439fbba9f655ded06L101) is the bit that handles the None... `type_generator()` actually seems to fail if I handle the empty generator correctly.

**Comment by jameshiebert** [comment]
> type_generator() actually seems to fail if record_generator() is a correct empty generator.

Really?! Man, the more I read this code, the more that I cannot wait to burn it all to the ground. When we move to python 3 and can just `yield from`, it's going to be awesome.

**Comment by jameshiebert** [comment]
So @corviday I ran your patch and was still able to get [certain requests](https://github.com/pacificclimate/pydap.responses.netcdf/pull/5/files#diff-eea9b0184211e212019dd4e873c8f609R13) on a [file without record variables](https://github.com/pacificclimate/pydap.responses.netcdf/pull/5/files#diff-e9e78e8c774fbc5494192cadf869a6fd) to drop into the infinite `while` loop.

I *think* that [I've fixed it](https://github.com/pacificclimate/pydap.responses.netcdf/pull/5/files#diff-79b78de6ebc6534439fbba9f655ded06R130), but I'm going to do another day of testing in case we're missing something.

**Comment by jameshiebert** [comment]
I've written some [comprehensive testing](https://github.com/pacificclimate/pdp/tree/bugfix/bccaqv2) that is possible (but not easy) to run in the pdp repo.

What it's turning up is that many of the BCCAQv2 datasets return data that has a different content-length than what the response says it *should* have. However, the NetCDF library happily opens up the responses without error. It's possible that it's creating a well-formed file, but with some offset mistake somewhere (most of the error files are off by 2-6 bytes) that makes the data == garbage anywhere after the offest problem.

We should discuss our course of action here. Do we release this fix while continuing to work on the offset problem, or should we get everything fixed before release?

**Comment by jameshiebert** [comment]
OK @corviday and I agreed that, barring evidence that this fix causes the offset problem, we're going to merge this fix and [open a new issue](https://github.com/pacificclimate/pydap.responses.netcdf/issues/6) for the offset problem.

**Review by jameshiebert — APPROVED** [review]

**Pull request merged**
